# Generated by Django 5.2.8 on 2025-11-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name="Username [Unused, leftover from django's defaults]"),
        ),
    ]
