# Generated by Django 5.2.8 on 2025-11-14 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_username'),
        ('content', '0003_alter_post_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography', models.TextField(default='', verbose_name='Biography')),
                ('school', models.CharField(max_length=512, verbose_name='School')),
                ('subject', models.CharField(max_length=512, verbose_name='Subject')),
                ('years_of_experience', models.PositiveIntegerField(default=0, verbose_name='Years of Experience')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('non-binary', 'Non-Binary'), ('other', 'Other')], max_length=255, verbose_name='Gender')),
                ('grades', models.ManyToManyField(related_name='teachers', to='content.grade', verbose_name='Grades')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
