# Generated by Django 5.2.8 on 2025-11-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_teacherprofile_picture'),
        ('content', '0003_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='grades',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='content.grade', verbose_name='Grades'),
        ),
    ]
