# Generated by Django 5.2.8 on 2025-11-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_teacherprofile_grades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='biography',
            field=models.TextField(blank=True, default='', verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('non-binary', 'Non-Binary'), ('other', 'Other')], default='female', max_length=255, verbose_name='Gender'),
        ),
    ]
