# Generated by Django 5.2.8 on 2025-12-09 19:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Name')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('length_of', models.DurationField(verbose_name='Length of Study')),
                ('consent_form', models.FileField(upload_to='research/studies/consent-forms/')),
            ],
        ),
        migrations.CreateModel(
            name='IRBDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Name')),
                ('file', models.FileField(upload_to='research/studies/documentation/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('.docx', '.pdf'), message='Invalid File format, must be either PDF or Word Docx.')], verbose_name='File')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='irb_documentation', to='research.study')),
            ],
        ),
        migrations.CreateModel(
            name='ConsentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('studies', models.ManyToManyField(related_name='consentees', to='research.study')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Name')),
                ('message', models.TextField(blank=True, default='', verbose_name='Message')),
                ('link', models.URLField(verbose_name='Link to Survey')),
                ('cadence', models.CharField(choices=[('once', 'Once'), ('yearly', 'YEARLY'), ('bi-yearly', 'Bi Yearly (Every 6 Months)')], max_length=255, verbose_name='Cadence')),
                ('last_notice', models.DateTimeField(blank=True, null=True, verbose_name='Last Notice')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='research.study')),
            ],
        ),
    ]
