# Generated by Django 5.2.8 on 2025-12-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentprofile',
            name='is_open',
            field=models.BooleanField(default=False, verbose_name='Is Open to Studies'),
            preserve_default=False,
        ),
    ]
