# Generated by Django 5.2.8 on 2025-11-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0002_alter_grade_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(verbose_name='Query')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Views')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Likes')),
                ('grades', models.ManyToManyField(related_name='+', to='content.grade')),
                ('results', models.ManyToManyField(related_name='+', to='content.post')),
                ('standards', models.ManyToManyField(related_name='+', to='content.standard')),
            ],
        ),
    ]
