# Generated by Django 5.2.8 on 2025-11-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='searched_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Searched At'),
        ),
    ]
