# Generated by Django 5.2.8 on 2025-12-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_comment_options_comment_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['-sort_order']},
        ),
        migrations.AddField(
            model_name='grade',
            name='sort_order',
            field=models.IntegerField(default=0, unique=True, verbose_name='Sort Order'),
            preserve_default=False,
        ),
    ]
