# Generated by Django 5.2.8 on 2025-12-16 19:19

from django.db import migrations

GRADES = (
    (
        "Pre-school",
        1,
    ),
    (
        "Pre-K",
        2,
    ),
    ("Kindergarten", 3),
    ("1st", 4),
    ("2nd", 5),
    ("3rd", 6),
    ("4th", 7),
    ("5th", 8),
    ("6th", 9),
    ("7th", 10),
    ("8th", 11),
    ("9th", 12),
    ("10th", 13),
    ("11th", 14),
    ("12th", 15),
    ("Undergraduate", 16),
)


def populate_grades(apps, schema_editor):
    """Populate the Grades table."""
    Grade = apps.get_model("content", "Grade")
    for grade, sort_idx in GRADES:
        Grade.objects.create(name=grade, sort_order=sort_idx)


def unpopulate_grades(apps, schema_editor):
    """Unpopulate the Grades Table."""
    Grade = apps.get_model("content", "Grade")
    Grade.objects.filter(name__in=[x[0] for x in GRADES]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0006_alter_grade_options_grade_sort_order"),
    ]

    operations = [
        migrations.RunPython(populate_grades, unpopulate_grades),
    ]
