# Generated by Django 5.2.8 on 2025-12-16 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_populate_grade_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['sort_order']},
        ),
    ]
